spring:
  datasource:
      driver-class-name: org.postgresql.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml #Mapper的xml文件
  type-aliases-package: com.makelife.*.domain #实体类的包

mapper:
  mappers: com.makelife.utils.data.TkMapper
  not-empty: false
  identity: postgresql